name: Build and Release Weather CLI Tool

on:
  push:
    branches:
      - dev
      - main

env:
  BUILD_NUMBER: ${{ github.run_number }}
  BUILD_DIR: "dev-merger-build"

permissions:
  contents: write  # Grant write permissions for releases

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use system-installed Python 3.9
        run: |
          python3.9 --version
          pip3.9 install --upgrade pip
          pip3.9 install requests pyinstaller

      - name: Build the project
        run: |
          pyinstaller --onefile weather.py
          if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            mv dist/weather dist/weather-dev-${{ env.BUILD_NUMBER }}
          elif [ "${{ github.ref }}" = "refs/heads/main" ]; then
            mv dist/weather dist/weather-main-${{ env.BUILD_NUMBER }}
          fi

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: weather-tool-${{ github.ref_name }}
          path: dist/

  store_dev_build:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: weather-tool-dev
          path: dist/

      - name: Create GitHub Release for Dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="dev-${{ env.BUILD_NUMBER }}"
          gh release create "$VERSION" dist/weather-dev-${{ env.BUILD_NUMBER }} \
            --title "Dev Build $VERSION" \
            --notes "Automated dev build." \
            --prerelease

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: weather-tool-main
          path: dist/

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="v${{ env.BUILD_NUMBER }}"
          gh release create "$VERSION" dist/weather-main-${{ env.BUILD_NUMBER }} \
            --title "Build $VERSION" \
            --notes "Automated build and release."
